services:
  mysql-develop:
    image: mysql:8.0
    container_name: sgh-mysql-develop
    restart: always
    env_file:
      - .env.dev
    ports:
      - "3306:3306"
    networks:
      - network_develop
    volumes:
      - mysql_data_develop:/var/lib/mysql
      - "./backups/develop:/backups/mysql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - com.sgh.group=sgh
      - com.sgh.environment=develop

volumes:
  mysql_data_develop:

networks:
  network_develop: