services:
  mysql-staging:
    image: mysql:8.0
    container_name: sgh-mysql-staging
    restart: always
    env_file:
      - .env.staging
    ports:
      - "3307:3306"
    networks:
      - network_staging
    volumes:
      - mysql_data_staging:/var/lib/mysql
      - "./backups/staging:/backups/mysql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - com.sgh.group=sgh
      - com.sgh.environment=staging

volumes:
  mysql_data_staging:

networks:
  network_staging:
